<?php
/**
 * Copyright (c) 2017.
 *
 * @author Alexander Zagovorichev <zagovorichev@gmail.com>
 */

use App\Form;
use App\FormReport;
use Illuminate\Database\Seeder;

class FormReportsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (App::environment('production') && FormReport::all()->count()) {
            return;
        } elseif (!App::environment('production')) {
            FormReport::truncate();
            factory(FormReport::class, 10)->create([
                'form_id' => function () {
                    return factory(Form::class)->create([
                        'title' => 'Accident Report Form',
                        'description' => 'Form has been generated by ModelFactory for FormReport',
                        'template' => '<p>Form for :className</p><p>Generated by <b>:generatorName</b></p>',
                        'variables' => 'className,generatorName',
                    ])->id;
                },
            ]);
        }
    }
}
