<?php
/**
 * Copyright (c) 2018.
 *
 * @author Alexander Zagovorichev <zagovorichev@gmail.com>
 */

use App\Form;
use App\FormReport;
use Faker\Generator as Faker;

$factory->define(FormReport::class, function (Faker $faker) {
    return [
        'form_id' => function () {
            return factory(Form::class)->create([
                'title' => 'Accident Report Form',
                'description' => 'Form has been generated by ModelFactory for FormReport',
                'template' => '<p>Form for :className</p><p>Generated by <b>:generatorName</b></p>',
                'variables' => 'className,generatorName',
            ])->id;
        },
        'values' => json_encode(['className' => FormReport::class, 'generatorName' => 'ModelFactory']),
    ];
});
